### PR TITLE
add description support for Parser

### LINKED ISSUE #74: can I give tap a parser description??
Hi.  
I am trying to change old codes to TAP. 
However, it seems that tap does not have description like argparser.
For example
`parser = ArgumentParser(description='this is a sample parser')`
Does tap has parser description?
plus, metavar option and shortcuts like this 
`parser.add_argument(
        '--very_long_arg',
        '-a',
        type=int,
        default=1,
        metavar='N',
        help='it is a very long argument,
    )`

### PR DESCRIPTION
**Pull request by wj-Mcat**
Fix:  https://github.com/swansonk14/typed-argument-parser/issues/74

- [x] enable `__doc__` as description and help info 
- [x] add unittest for this feature
- [x] bump version

### CODE REVIEW

**Comment by wj-Mcat** [comment]
ping @swansonk14

**Comment by martinjm97** [comment]
Hi @wj-Mcat, 

This looks great! Thank you for contributing! I just green-lighted the automatic tests. @swansonk14 and I will meet this weekend to discuss this feature. 

Best, 
Jesse

**Comment by wj-Mcat** [comment]
ping @martinjm97  How do you think about this feature ?

**Comment by wj-Mcat** [comment]
reping @martinjm97

**Comment by martinjm97** [comment]
Hi @wj-Mcat,

Sorry for the delay and thank you again for contributing! We really like this idea. It'll make Tap even more convenient.

Best, 
Kyle and Jesse

**Comment by scarf005** [comment]
@martinjm97 could you upload the updated version (1.7.3) on pypi? 
it's still 1.7.2 despite this PR being merged: https://pypi.org/project/typed-argument-parser/

**Pull request merged**
